### ISSUE TITLE
Case Print

### ISSUE THREAD

**Issue by MMFW** [dr-mod/little-sun-gazer#2]
Awesome project! I've put the BoM in my shopping cart. Any idea when you'll drop the .stl for the case?

**Comment by TurboKia** [comment]
Still waiting on STL.  Are there any updates on the project?

**Comment by dr-mod** [comment]
Hi, I apologize for the long wait. I've just uploaded the model here: https://www.printables.com/model/358204-little-sun-gazer 
As for the updates, I've come up with a few improvements for the project so hopefully will be able to implement them soon.

**Comment by TurboKia** [comment]
👍On Jan 3, 2023 3:35 PM, Dmytro Panin ***@***.***> wrote:
Hi, I apologize for the long wait. I've just uploaded the model here: https://www.printables.com/social/306904-dmytro-panin/models
As for the updates, I've come up with a few improvements for the project so hopefully will be able to implement them soon.
